### ISSUE TITLE
problem for compile atm-cop (GTC2018_demo)

### ISSUE THREAD

**Issue by lj-cug** [uturuncoglu/RegESM#21]
Dear Sir:
      I use my Ubuntu 18.04 installed with gcc, g++, gfortran (v7.5) and mpich2-3.3 to compile the GTC2018_demo tutorial, and some compilation problems happened. Before this, I have installed all the libraries and ATM, OCN, Paraview_5.4 successfully. But When I compile the driver (RegESM_1.1), the errors are:
/usr/bin/ld: cop/libcop.a(adaptor.o): undefined reference to symbol '_ZNSt8ios_base4InitD1Ev@@GLIBCXX_3.4'
/usr/lib/gcc/x86_64-linux-gnu/7//libstdc++.so: error adding symbols: DSO missing from command line

In RegESM, the command I used is:
./bootstrap.sh
./configure --prefix=`pwd` --with-atm=../../atm/r6146 --with-paraview=/home/lijian/paraview-5.4.1/build  CC=gcc FC=gfortran MPIFC=mpif90 CXX=g++

The solution on the Internet tells me to use g++ instead of gcc, which can solve the problem. But I find mpicxx was used to compile the cop including adaptor.cpp and grid.cpp.
Could you please help me to analyze the configuration?
Thanks
Li Jian

**Comment by uturuncoglu** [comment]
@lj-cug I am not sure about the error exactly since it is coming from C++ compiler that you are using it. There is some helpful information in the following link 

https://stackoverflow.com/questions/23286062/undefined-reference-to-symbol-znst8ios-base4initd1evglibcxx-3-4-building-op

It seems that you are already using `g++` as C++ compiler, which seems okay. BTW, `mpicxx` is just an wrapper. Could you send me the output of `mpicxx -v` command. BTW, you said that you compiled ParaView successfully. Is it working successfully in your case. BTW, all the components need to be compiled with same compilers etc. and needs to be consistent in terms of the build environment.

**Comment by lj-cug** [comment]
Dear Sir:
     Now I can solve the compilation problem, my solution is adding option "-lstdc++" in the line 110 of the auto-generated Makefile from the advice on Internet. 
  But When I used the same compilation steps to compile RegESM_1.2.0, many "undefined reference to 'vtkCP***" cannot be linked. So I want to know what's the version of Paraview was needed in RegESM_1.2.0.
     Besides, can I use higher version ParaView within the RegESM_1.2? I need the first-hand experience to use RegESM.
Thanks!
Best Regards
Li Jian

**Comment by lj-cug** [comment]
Another question, when I run regesm.x, I have some question about regcm.in
(1) inpglob is the path for ICBC global input datasets
(2) inpter is the path for SURFACE data
These two data file, I cannot fine in the GTC2018_demo. Because I am a green hand to the RegCM model. 
These days I try to learn RegCM model. I want to run RegESM first, then study it deeply.
Could you please help me! 
Sorry for my so many questions. Much thanks!
Could you give me your available e-mail? There will be many problems when I use RegESM, I need your help!

**Comment by uturuncoglu** [comment]
@lj-cug I suggest you to learn or gain experience about each individual model components before going to fully coupled. BTW, you will be sure that the standalone model component such as RegCM is working properly and producing reasonable output when you compare it with the available observations. Then you could try to couple them to see the interaction Mong components. So, going directly to RegESM is not the way that I suggest. Here are the mode detailed answer for your previous questions,

- If you check the GMD paper - https://gmd.copernicus.org/articles/12/233/2019/ you could find the details of each component and their version information. In that time I used ParaView 5.4.1. You could also access the version of the RegESM that is used in that work through the Zenodo. So check these links, https://zenodo.org/record/1307212#.YTrbbi2cYXo and https://zenodo.org/record/1474753#.YTrbcy2cYXo. Since in situ visualization adds extra complexity to the coupled system and requires deep knowledge about the different components, it would be nice to go step by step from standalone model runs for each component and then coupled model and then a configuration with in situ visualization. Otherwise, it would be impossible to setup the model and make meaningful simulation and/or in situ analysis. In your special case, having error like `undefined reference to 'vtkCP***` indicates that you are not using compatible ParaView version. You also consider that ParaView is also involving and its interface is changing and it is hard to test all the versions with the RegESM and in situ visualization is a major task that needs funding and at least couple of software engineers that we don't have at this point. 
- Please look at those Zenodo links to find more information. It is hard to put all the files to a public place since those are very big files. So, because of this reason, you need to setup your own case step by step from simple to complex and then using existing Zenodo files as reference you could get benefit of RegESM and also in situ visualization. It is hard for me to help you for every steps since I have other staff but I could guide you in the critical points that you need suggestion.

I hope my suggestions and answers will help you.

**Comment by lj-cug** [comment]
Thanks for your kindly advice. Now I have installed successfully all the necessary libraries and components in my computer with one CPU have 8 cores and one NVIDIA Quadro RTX4000 card. Then I try to run ATM-COP case.
In the namelist.rc file, I set "PETs: 4 0 0 0 4"
Then run: mpirun -np 4 ./regesm.x regcm.in
But the errors happened as following:

20210911 175628.875 ERROR            PET3 ESMF_Config.F90:924 ESMF_ConfigFindLabel Not found  - label CoProcessorHaloWidth: not found
20210911 175628.875 ERROR            PET3 util/mod_config.F90:614 Not found  - Passing error in return code
20210911 175628.875 ERROR            PET3 regesm.F90:58 Not found  - Passing error in return code
20210911 175628.875 INFO             PET3 Finalizing ESMF

I try to use paraview_5.4 compiled using VTK_USE_OFFSCREE_EGL and VTK_USE_X, the same above-mentioned errors happened.
I get confused with the situation that I run the regesm.x in my personal computer (not cluster). Does this cause the problem?
Hope for your help, Thanks!

**Comment by lj-cug** [comment]
Dear Sir:
    Now I can run the standalone RegCM 4.6 in GTC2018_demo sucessfully. But when I run the regesm.x with: mpirun -np regesm.x regcm.in, some errors happened at the following step:

Opening new output file /home/lijian/GTC2018_demo/output//DOM1_SRF.2005082700.nc     (until this step, both runnings of standalone regcm and regesm.x are the same)

 PET(000) - DE(00) - PTR/ATM/GRD/CROSS    :        1      43       1     118 T F F T     
 PET(000) - DE(00) - DAT/ATM/GRD/CROSS    :        1      43       1     118 T F F T
 PET(007) - DE(00) - PTR/ATM/GRD/CROSS    :      129     170     119     235 F T T F
 PET(007) - DE(00) - DAT/ATM/GRD/CROSS    :      129     169     119     234 F T T F

And the PET0.ESMF_LogFile told me that:
20210912 102636.110 ERROR            PET0 ESMF_Comp.F90:1503 ESMF_CompGet Invalid object  - requested Clock object is not present.
20210912 102636.110 ERROR            PET0 ESMF_GridComp.F90:1129 ESMF_GridCompGet Invalid object  - Internal subroutine call returned Error
20210912 102636.110 ERROR            PET0 mod_esmf_atm.F90:488 Invalid object  - Passing error in return code
20210912 102636.110 ERROR            PET0 ATM:src/addon/NUOPC/src/NUOPC_Model.F90:259 Invalid object  - Passing error in return code
20210912 102636.110 ERROR            PET0 regesm:src/addon/NUOPC/src/NUOPC_Driver.F90:2213 Invalid object  - Phase 'IPDv00p3' Initialize for modelComp 1: ATM did not return ESMF_SUCCESS
20210912 102636.110 ERROR            PET0 regesm:src/addon/NUOPC/src/NUOPC_Driver.F90:1688 Invalid object  - Passing error in return code
20210912 102636.110 ERROR            PET0 regesm:src/addon/NUOPC/src/NUOPC_Driver.F90:388 Invalid object  - Passing error in return code
20210912 102636.110 ERROR            PET0 regesm.F90:94 Invalid object  - Passing error in return code
20210912 102636.110 INFO             PET0 Finalizing ESMF

I have no experience about using ESMF, so could you please give me some hints about the error?
Another strange thing is about the used PETs in namelist.rc: if I use "PETs: 4 0 0 0 4" and run regesm.x, the RegCM model component cannot run normally, and if I use "PETs: 8 0 0 0 8" , it's OK but the above-mentioned problem happeded. It seems that the configuration of PETs affects the running of RegCM in Regesm. AND I can run any np number in the standalone RegCM model.
Thanks for your help!

**Comment by lj-cug** [comment]
Dear Sir:
        Now I can run Regesm.x with Paraview_5.4. 
(1) But there are still some problems showing on the screen.
It seems that in every processor, it told me: check grid for input atm_input3d - NOT DEFINED !!!
        There are many states files. Should I put atm_input3d related file in somewhere? There's no enough hints in the github information.

(2) In every step for in-situ visualization, the PNG file will be stored in the disk, How could I switch off the storing? 
(3) I run regesm.x on my PC installed with one CPU having 8 cores and one NVIDIA QUadro GPU card. How Can I use the in-situ rendering when I compile ParaView_5.4? I get confused the multi-process rendering algorithm. My aim is that the headless rendering or off-screen rendering was conducted on 7 processes, and the composited rendered picture can be played on the master process (rank=0）. Is this available?
After I can control and run RegESM, I will study the components step by step. I have experience at using atm and ocn models, but ESMF should be studied in my plan.
Thanks!

**Comment by uturuncoglu** [comment]
Here are my comments,

(1) No, atm_input3d is the port that can be used under ParaView. So, this special port basically carries ATM 3d fields. To activate that port you need to export 3d fields from ATM to COP component. You could see the example exfield.tbl files in the https://github.com/uturuncoglu/RegESM/blob/master/docs/04_Usage.md. Such as `ulev:air_wind_u:3d:bilinear:cross:cross:m/s:m/s:1.0:0.0:F` is a definition for 3d fields and this needs to be under `atm2cop` section.

(2) If you don't want to store PNG files you need to modify your co-processing script (Python) and disable writing png files. I am not sure exact part that writes the Png files but I think you could find it in the Python script easily.

(3) If you don't want to store PNGs and want to live rendering then you need to activate it again in your Python co-processing script. I have no example for it but if you look at the script itself you could find more information. The rendering also depends on the Visualization pipeline that you use. Some filters support multi-GPU and multi-processor and some are not. You need to refer ParaView documentation for it.
